create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table memo
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(255),
    primary key (id)
);